

services:
  namenode:
    build: ./hadoop
    container_name: namenode
    hostname: namenode
    ports:
      - "9870:9870"  # HDFS namenode web UI
      - "8020:8020"  # HDFS namenode
    environment:
      - CLUSTER_NAME=hadoop-cluster
    env_file:
      - ./hadoop.env
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    command: ["hdfs", "namenode"]
    networks:
      - hadoop_network

  datanode1:
    build: ./hadoop
    container_name: datanode1
    hostname: datanode1
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    command: ["hdfs", "datanode"]
    networks:
      - hadoop_network

  mysql:
    build: ./mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: transactional_db
      MYSQL_USER: sqoop_user
      MYSQL_PASSWORD: sqoop_password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - hadoop_network

  hive-server:
    build:
      context: .
      dockerfile: hive/Dockerfile
    container_name: hive-server
    depends_on:
      - namenode
      - datanode1
    ports:
      - "10000:10000"  # HiveServer2
      - "10002:10002"  # Hive web UI
    env_file:
      - ./hadoop.env
    environment:
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionURL=jdbc:derby:;databaseName=/opt/hive/metastore_db;create=true
      - HIVE_SITE_CONF_hive_metastore_warehouse_dir=hdfs://namenode:8020/user/hive/warehouse
    volumes:
      - hive_data:/opt/hive/data
      - hive_metastore_db:/opt/hive/metastore_db # Persistent metastore
      - ./scripts:/scripts
    networks:
      - hadoop_network

  sqoop:
    build:
      context: .
      dockerfile: sqoop/Dockerfile
    container_name: sqoop
    depends_on:
      - namenode
      - mysql
      - hive-server
    volumes:
      - ./scripts:/scripts
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network

networks:
  hadoop_network:
    driver: bridge

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  mysql_data:
  hive_data:
  hive_metastore_db:
